### ISSUE TITLE
CreditCardCheck icon not found

### ISSUE THREAD

**Issue by juvs** [vyperium/mdi-dart#5]
CreditCardCheck icon not found, also CreditCardCheckOutline

**Comment by pepsighan** [comment]
CreditCardCheck does not seem to be available at [MaterialDesign-SVG](https://github.com/Templarian/MaterialDesign-SVG). We generate the bindings in dart using their lib `@mdi/util` and `@mdi/svg`.

I won't be able to make changes till the upstream includes those icons in the above libs. So, I would suggest you to post issues with them.

**Comment by pepsighan** [comment]
CreditCardCheck has now been added is `3.0.0`.
